os:
  - linux

language: php

php:
  - '7.4'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - touch db.sqlite
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 14.15.0
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install

script:
  - php artisan migrate
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production


before_deploy:
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi

deploy:
  skip_cleanup: true
  provider: script
  script: travis/deploy.sh
  on:
    branch: master
