os:
  - linux

language: php

php:
  - '8.0'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - touch db.sqlite
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 14.15.0
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install

script:
  - php artisan migrate
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
